language: cpp

sudo: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: 
        - CC=gcc-5
        - CXX=g++-5
        - ROOT_VERSION=5.34.36 
        - PATH=/usr/lib/ccache:${PATH}:${TRAVIS_BUILD_DIR}/install/bin LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${TRAVIS_BUILD_DIR}/install/lib
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: 
        - CC=clang-3.8
        - CXX=clang++-3.8
        - ROOT_VERSION=5.34.36 
        - PATH=/usr/lib/ccache:${PATH}:${TRAVIS_BUILD_DIR}/install/bin LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${TRAVIS_BUILD_DIR}/install/lib

addons:
  apt:
    packages:
      - x11-common
      - libx11-6
      - x11-utils
      - libX11-dev
      - libgsl0-dev
      - gsl-bin
      - libxpm-dev
      - libxft-dev
      - gfortran
      - build-essential
      - libjpeg-turbo8-dev
      - libjpeg8-dev
      - libjpeg-dev
      - libtiff4-dev
      - libxml2-dev
      - libssl-dev
      - libgnutls-dev
      - libgmp3-dev
      - libpng12-dev
      - libldap2-dev
      - libkrb5-dev
      - freeglut3-dev
      - libfftw3-dev
      - python-dev
      - libmysqlclient-dev
      - libgif-dev
      - libiodbc2
      - libiodbc2-dev
      - subversion
      - libxext-dev
      - libxmu-dev
      - libimlib2
      - gccxml

cache:
  directories:
    - $HOME/.ccache

install:
  # install ROOT. Not in Ubuntu 12.04, only later again... Travis still uses stone-aged 12.04. 
  - mkdir root
  - cd root
  - wget http://root.cern.ch/download/root_v${ROOT_VERSION}.source.tar.gz
  - tar xf root_v${ROOT_VERSION}.source.tar.gz
  - cd root
  - mkdir -p ${TRAVIS_BUILD_DIR}/install/
  - ./configure linuxx8664gcc --enable-explicitlink --minimal --prefix=${TRAVIS_BUILD_DIR}/install/root --etcdir=${TRAVIS_BUILD_DIR}/install/root/etc/root
  - make
  - make install
  - source ${TRAVIS_BUILD_DIR}/install/root/bin/thisroot.sh

  - export CXX="${COMPILER}"

before_script:
  - mkdir -p ${TRAVIS_BUILD_DIR}/build
  - mkdir -p ${TRAVIS_BUILD_DIR}/install
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=${TRAVIS_BUILD_DIR}/install ../

script:
  - env
  - make
  - make install
  - cd ${TRAVIS_BUILD_DIR}/install
  - rootStaticAnalyzer --help
  - rootStaticAnalyzer -d -c "^TObj.*" -D
